version: 0.0
os: linux
files:
  # unzip en ~/app/release
  - source: /
    destination: /home/ubuntu/app/release
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/preInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    # Inicia la aplicación com ubuntu
    - location: scripts/runServer.sh
      timeout: 300
      runas: root
  ApplicationStop:
  # Para la aplicación
    - location: scripts/stopServer.sh
      timeout: 300
      runas: root